/**
 * AUTO-GENERATED by scripts/gen-evdev-keys.cjs — do not edit by hand.
 *
 * nut.js `Key` enum value -> Linux evdev hardware code.
 * The control clients built from this repo speak nut.js numbering; the Wayland
 * RemoteDesktop portal speaks evdev numbering.  134 nut.js keys, of which
 * 132 have an evdev equivalent (2 dropped: Fn, Clear).
 *
 * Regenerate:  node scripts/gen-evdev-keys.cjs
 */

/** nut.js Key enum value -> evdev code. 0 means "no equivalent, skip". */
export const NUT_KEY_TO_EVDEV: Readonly<Record<number, number>> = {
  0: 1, // Escape -> KEY_ESC
  1: 59, // F1 -> KEY_F1
  2: 60, // F2 -> KEY_F2
  3: 61, // F3 -> KEY_F3
  4: 62, // F4 -> KEY_F4
  5: 63, // F5 -> KEY_F5
  6: 64, // F6 -> KEY_F6
  7: 65, // F7 -> KEY_F7
  8: 66, // F8 -> KEY_F8
  9: 67, // F9 -> KEY_F9
  10: 68, // F10 -> KEY_F10
  11: 87, // F11 -> KEY_F11
  12: 88, // F12 -> KEY_F12
  13: 183, // F13 -> KEY_F13
  14: 184, // F14 -> KEY_F14
  15: 185, // F15 -> KEY_F15
  16: 186, // F16 -> KEY_F16
  17: 187, // F17 -> KEY_F17
  18: 188, // F18 -> KEY_F18
  19: 189, // F19 -> KEY_F19
  20: 190, // F20 -> KEY_F20
  21: 191, // F21 -> KEY_F21
  22: 192, // F22 -> KEY_F22
  23: 193, // F23 -> KEY_F23
  24: 194, // F24 -> KEY_F24
  25: 99, // Print -> KEY_SYSRQ
  26: 70, // ScrollLock -> KEY_SCROLLLOCK
  27: 119, // Pause -> KEY_PAUSE
  28: 41, // Grave -> KEY_GRAVE
  29: 2, // Num1 -> KEY_1
  30: 3, // Num2 -> KEY_2
  31: 4, // Num3 -> KEY_3
  32: 5, // Num4 -> KEY_4
  33: 6, // Num5 -> KEY_5
  34: 7, // Num6 -> KEY_6
  35: 8, // Num7 -> KEY_7
  36: 9, // Num8 -> KEY_8
  37: 10, // Num9 -> KEY_9
  38: 11, // Num0 -> KEY_0
  39: 12, // Minus -> KEY_MINUS
  40: 13, // Equal -> KEY_EQUAL
  41: 14, // Backspace -> KEY_BACKSPACE
  42: 110, // Insert -> KEY_INSERT
  43: 102, // Home -> KEY_HOME
  44: 104, // PageUp -> KEY_PAGEUP
  45: 69, // NumLock -> KEY_NUMLOCK
  46: 98, // Divide -> KEY_KPSLASH
  47: 55, // Multiply -> KEY_KPASTERISK
  48: 74, // Subtract -> KEY_KPMINUS
  49: 15, // Tab -> KEY_TAB
  50: 16, // Q -> KEY_Q
  51: 17, // W -> KEY_W
  52: 18, // E -> KEY_E
  53: 19, // R -> KEY_R
  54: 20, // T -> KEY_T
  55: 21, // Y -> KEY_Y
  56: 22, // U -> KEY_U
  57: 23, // I -> KEY_I
  58: 24, // O -> KEY_O
  59: 25, // P -> KEY_P
  60: 26, // LeftBracket -> KEY_LEFTBRACE
  61: 27, // RightBracket -> KEY_RIGHTBRACE
  62: 43, // Backslash -> KEY_BACKSLASH
  63: 111, // Delete -> KEY_DELETE
  64: 107, // End -> KEY_END
  65: 109, // PageDown -> KEY_PAGEDOWN
  66: 71, // NumPad7 -> KEY_KP7
  67: 72, // NumPad8 -> KEY_KP8
  68: 73, // NumPad9 -> KEY_KP9
  69: 78, // Add -> KEY_KPPLUS
  70: 58, // CapsLock -> KEY_CAPSLOCK
  71: 30, // A -> KEY_A
  72: 31, // S -> KEY_S
  73: 32, // D -> KEY_D
  74: 33, // F -> KEY_F
  75: 34, // G -> KEY_G
  76: 35, // H -> KEY_H
  77: 36, // J -> KEY_J
  78: 37, // K -> KEY_K
  79: 38, // L -> KEY_L
  80: 39, // Semicolon -> KEY_SEMICOLON
  81: 40, // Quote -> KEY_APOSTROPHE
  82: 28, // Return -> KEY_ENTER
  83: 75, // NumPad4 -> KEY_KP4
  84: 76, // NumPad5 -> KEY_KP5
  85: 77, // NumPad6 -> KEY_KP6
  86: 42, // LeftShift -> KEY_LEFTSHIFT
  87: 44, // Z -> KEY_Z
  88: 45, // X -> KEY_X
  89: 46, // C -> KEY_C
  90: 47, // V -> KEY_V
  91: 48, // B -> KEY_B
  92: 49, // N -> KEY_N
  93: 50, // M -> KEY_M
  94: 51, // Comma -> KEY_COMMA
  95: 52, // Period -> KEY_DOT
  96: 53, // Slash -> KEY_SLASH
  97: 54, // RightShift -> KEY_RIGHTSHIFT
  98: 103, // Up -> KEY_UP
  99: 79, // NumPad1 -> KEY_KP1
  100: 80, // NumPad2 -> KEY_KP2
  101: 81, // NumPad3 -> KEY_KP3
  102: 28, // Enter -> KEY_ENTER
  103: 29, // LeftControl -> KEY_LEFTCTRL
  104: 125, // LeftSuper -> KEY_LEFTMETA
  105: 125, // LeftWin -> KEY_LEFTMETA
  106: 125, // LeftCmd -> KEY_LEFTMETA
  107: 56, // LeftAlt -> KEY_LEFTALT
  108: 57, // Space -> KEY_SPACE
  109: 100, // RightAlt -> KEY_RIGHTALT
  110: 126, // RightSuper -> KEY_RIGHTMETA
  111: 126, // RightWin -> KEY_RIGHTMETA
  112: 126, // RightCmd -> KEY_RIGHTMETA
  113: 139, // Menu -> KEY_MENU
  114: 97, // RightControl -> KEY_RIGHTCTRL
  116: 105, // Left -> KEY_LEFT
  117: 108, // Down -> KEY_DOWN
  118: 106, // Right -> KEY_RIGHT
  119: 82, // NumPad0 -> KEY_KP0
  120: 83, // Decimal -> KEY_KPDOT
  122: 113, // AudioMute -> KEY_MUTE
  123: 114, // AudioVolDown -> KEY_VOLUMEDOWN
  124: 115, // AudioVolUp -> KEY_VOLUMEUP
  125: 164, // AudioPlay -> KEY_PLAYPAUSE
  126: 166, // AudioStop -> KEY_STOPCD
  127: 201, // AudioPause -> KEY_PAUSECD
  128: 165, // AudioPrev -> KEY_PREVIOUSSONG
  129: 163, // AudioNext -> KEY_NEXTSONG
  130: 168, // AudioRewind -> KEY_REWIND
  131: 208, // AudioForward -> KEY_FASTFORWARD
  132: 200, // AudioRepeat -> KEY_PLAYCD
  133: 171, // AudioRandom -> KEY_CONFIG
};

/** Look up the evdev code for a nut.js key value, or 0 when unmapped. */
export function nutKeyToEvdev(nutKey: number): number {
  return NUT_KEY_TO_EVDEV[nutKey] || 0;
}
